### ISSUE TITLE
ss-redir TFO support

### ISSUE THREAD

**Issue by easyteacher** [shadowsocksrr/shadowsocksr-libev#12]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.5.6 with OpenSSL 1.0.2k  26 Jan 2017

### What operating system are you using?
Linux version 4.4.92 (buildbot@builds-02.infra.lede-project.org) (gcc version 5.4.0 (LEDE GCC 5.4.0 r3104-41de9a2) ) #0 SMP Tue Oct 17 17:46:20 2017

### What did you expect to see?
ss-redir supports TCP Fast Open.

**Comment by birdofprey** [comment]
I hope update default in Ssr rss

**Comment by birdofprey** [comment]
what create Ssr rss Server and client for Linux?

**Comment by Akkariiin** [comment]
you can direct use python as client. It have all the features.

**Comment by easyteacher** [comment]
Now I use ss-local+redsocks to implement TFO on my router. 

shadowsocks-libev (3.0.4-1) added support for TFO in ss-redir. 

If ss-redir in SSRR can support TFO, it will be better.

**Comment by easyteacher** [comment]
Close the ticket and reopen if needed.
