### ISSUE TITLE
编译问题/doc/shadowsocks-libev.xml does not validate (status 127)

### ISSUE THREAD

**Issue by paldier** [shadowsocksrr/shadowsocksr-libev#14]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.1

make[6]: Entering directory `/home/paldier/k3cb1/k3c/build_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_mr_eth_rt_72/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.1/doc'
  GEN      shadowsocks-libev.xml
  GEN      shadowsocks-libev.8
xmlto: /home/paldier/k3cb1/k3c/build_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_mr_eth_rt_72/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.1/doc/shadowsocks-libev.xml does not validate (status 127)
xmlto: Fix document syntax or use --skip-validation option
/usr/bin/xmllint: relocation error: /usr/bin/xmllint: symbol xmlLoadCatalogs, version LIBXML2_2.4.30 not defined in file libxml2.so.2 with link time reference

libxml2 2.9.3
libxslt 1.1.28
lxml 3.7.2
我应该如何修复，很可能是libxslt或者lxml造成的问题，在加入libxslt和lxml之前是可以编译成功的，加入之后就报这个错误了
$(eval $(call HostBuild))
$(eval $(call BuildPackage,libxslt))
$(eval $(call HostBuild))
$(eval $(call BuildPackage,lxml))

**Comment by Akkariiin** [comment]
这个项目中有shadowsocks-libev.xml这个文件吗？
你应该去问shadowsocksR-libev-openssl这个项目的维护者吧？

**Comment by paldier** [comment]
源代码其实是这边的，用过一些老版本的可以编译成功,比如d4904568c0bd7e0861c0cbfeaa43740f404db214

**Comment by Akkariiin** [comment]
[d4904568c0bd7e0861c0cbfeaa43740f404db214](https://github.com/shadowsocksrr/shadowsocksr-libev/commit/d4904568c0bd7e0861c0cbfeaa43740f404db214) 这不就是新版吗

我觉得你是不是该先去给 shadowsocksR-libev-openssl 项目提一个issue？两边一起来解决比较好？

**Comment by paldier** [comment]
Making all in doc
make[6]: Entering directory `/home/paldier/k3cb1/k3c/build_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_mr_eth_rt_72/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.1/doc'
  GEN      shadowsocks-libev.xml
  GEN      shadowsocks-libev.8
xmlto: /home/paldier/k3cb1/k3c/build_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_mr_eth_rt_72/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.1/doc/shadowsocks-libev.xml does not validate (status 127)
xmlto: Fix document syntax or use --skip-validation option
/usr/bin/xmllint: relocation error: /usr/bin/xmllint: symbol xmlLoadCatalogs, version LIBXML2_2.4.30 not defined in file libxml2.so.2 with link time reference
make[6]: *** [shadowsocks-libev.8] Error 137
rm shadowsocks-libev.xml
doc文件夹里的其实并非必需吧
下面是编译成功的版本项目里不含libxslt
`Making all in doc
make[5]: Entering directory `/home/paldier/k3c/UGW-7.1.1/build_dir/target-mips_mips32_uClibc-0.9.33.2_grx350_1600_mr_eth_rt_711/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.1/doc'
  GEN      shadowsocks-libev.xml
  GEN      shadowsocks-libev.8
  GEN      ss-local.xml
  GEN      ss-local.1
  GEN      ss-manager.xml
  GEN      ss-manager.1
  GEN      ss-nat.xml
  GEN      ss-nat.1
  GEN      ss-redir.xml
  GEN      ss-redir.1
  GEN      ss-server.xml
  GEN      ss-server.1
  GEN      ss-tunnel.xml
  GEN      ss-tunnel.1
  GEN      shadowsocks-libev.html
  GEN      ss-local.html
  GEN      ss-manager.html
  GEN      ss-nat.html
  GEN      ss-redir.html
  GEN      ss-server.html
  GEN      ss-tunnel.html
rm ss-server.xml ss-local.xml ss-redir.xml ss-nat.xml ss-tunnel.xml shadowsocks-libev.xml ss-manager.xml`

**Comment by paldier** [comment]
已解决，加--disable-documentation

**Comment by Yewenyu** [comment]
> 已解决，加--disable-documentation

你好，请问这个命令加在哪里
