### ISSUE TITLE
how into SSR V2RAY

### ISSUE THREAD

**Issue by birdofprey** [shadowsocksrr/shadowsocksr-libev#15]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
3.1.1

### What operating system are you using?
Debian Gnu/Linux 9.3

### What did you do?
how do you into ssr v2ray

### What did you expect to see?

when to join SSR V2RAY protocol support ,that's the best. tank you very math!!!freedomn

**Comment by Akkariiin** [comment]
What?
Please re-describe your problem without template.

**Comment by birdofprey** [comment]
when to join SSR V2RAY protocol support ,that's the best. tank you very math???

**Comment by birdofprey** [comment]
no ssr v2ray protocol its not happy

**Comment by Akkariiin** [comment]
you need make a issue on the V2ray project not here.

this way ; https://github.com/v2ray/v2ray-core/issues
