### ISSUE TITLE
libtoolT issue in configure

### ISSUE THREAD

**Issue by perqin** [shadowsocksrr/shadowsocksr-libev#20]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
Latest commit on branch *Akkariiin/develop*.

### What operating system are you using?
Arch Linux.

### What did you do?
Compile the source.
Run:
```
./configure --prefix=/home/perqin/.local/opt/shadowsocksrr-libev --enable-shared --enable-system-shared-lib
```

### What did you expect to see?
No error reported.

### What did you see instead?
I got these lines after finishing configure:
```
/usr/bin/rm: cannot remove 'libtoolT': No such file or directory
```

According to [https://bz.apache.org/bugzilla/show_bug.cgi?id=51726](https://bz.apache.org/bugzilla/show_bug.cgi?id=51726), it seems to be the problem in file `configure`. I modified L17962 from `$RM "$cfgfile"` to `$RM -f "$cfgfile"` and the complaining message gone. I'm wondering whether this is the correct solution.

**Comment by Akkariiin** [comment]
Thank you.

**Comment by Akkariiin** [comment]
694467d2a109739b74f595aa5fa5da35b4a6654a fixed
