### ISSUE TITLE
ss与ssrr共存

### ISSUE THREAD

**Issue by tianrking** [shadowsocksrr/shadowsocksr-libev#27]
怎么使 ss-libev与ssrr-libev共存呢

**Comment by Justsoos** [comment]
开多个虚拟机，按破娃文章配置，不要太简单。不仅ssr 和ss 共存，udp2raw，udpspeeder，kcptun，v2ray .... 都能共存
https://breakwa11.blogspot.hk/2016/11/blog-post.html
