### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Mondaydream** [shadowsocksrr/shadowsocksr-libev#28]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.4.8

### What operating system are you using?
iOS

### What did you do?
ssr

### What did you expect to see?
work for the ssr

### What did you see instead?
crash

### What is your config in detail (with all sensitive info masked)?
 @移植到iOS设备时，客户端发起新的请求，在local.c的建立起new_server函数出现指针异常，如截图 
<img width="833" alt="screen shot 2018-02-23 at 7 21 29 pm" src="https://user-images.githubusercontent.com/12235582/36592633-8f36215e-18d1-11e8-85e5-c50311684ea7.png">
这是参数的结构图
<img width="501" alt="screen shot 2018-02-23 at 7 23 36 pm" src="https://user-images.githubusercontent.com/12235582/36592644-9ebd6f24-18d1-11e8-9950-04a499af021b.png">
   @Akkariiin 找了很久的原因找不到，作者可以帮忙看看么感谢

**Comment by Mondaydream** [comment]
读了几天的code，大概了解libev的流程，每次建立新的连接都要建立对应的server，挂在这一步导致工程进行不下去，原因有点难找，求经历过的童鞋帮忙看看

**Comment by Akkariiin** [comment]
我不是太确定，之前读代码的时候这个ev_io的部分也感觉有点奇怪

**Comment by Abiu1314** [comment]
大哥，同样遇到这个问题，后面有解决么？

**Comment by TheWanderingCoel** [comment]
大佬,这边也遇到这个错误了,有解决吗？

**Comment by pang-w** [comment]
同样的问题，楼上的大佬们有解决吗？ @Mondaydream @Akkariiin @Amberler @TheWanderingCoel
