### ISSUE TITLE
Need tls1.2_ticket_fastauth support

### ISSUE THREAD

**Issue by setsunawang** [shadowsocksrr/shadowsocksr-libev#3]
### What version of shadowsocks-libev are you using?
Latest version maintained by breakwa11 with additional auth_chain_b support

### What operating system are you using?
Merlin ARM router

### What did you expect to see?
tls1.2_ticket_fast_auth

**Comment by Akkariiin** [comment]
tls1.2_ticket_fastauth only implement on C# client.
recently i try to transplant it to libev but i find that C# havea a state machine that different from python and libev.

so, transplant tls1.2_ticket_fastauth to other client may become a hard work.

**Comment by monokoo** [comment]
对于使用路由，玩游戏的用户来说，fastauth可能降低延迟，效果应该是有的，期待支持，谢谢

**Comment by xmj1** [comment]
fastauth期待支持，谢谢

**Comment by March-happy** [comment]
当然要啊

**Comment by sunsan05** [comment]
就初次握手的时候快一点，降低延迟还是请使用bbr以及使用可靠的QOS混淆

**Comment by redapple0204** [comment]
期待支持这个混淆。
