### ISSUE TITLE
shadowsocksr-libev是shadowsocksr的c++ 版本吗？和shadowsocks-libev什么关系？

### ISSUE THREAD

**Issue by zkpig123** [shadowsocksrr/shadowsocksr-libev#35]
明白了，ssr server没有libev版本，这是client的，但是文档什么的都写着ss还以为是ss的哈，应该是这样

**Comment by Justsoos** [comment]
我使用经验是 libev 支持新协议多，靠近最近版本，适合作客户端。
python 支持协议少，好久没人管了吧，但部署容易，适合作服务器。
但路由器只能跑 libev

**Comment by Akkariiin** [comment]
@Justsoos SSR这边所有新协议均先在Python上实现并测试，然后移植到其他实现上
所以你说的```python 支持协议少```是不存在的
