### ISSUE TITLE
2.5.2 版本编译问题

### ISSUE THREAD

**Issue by xsm1997** [shadowsocksrr/shadowsocksr-libev#5]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.2

### What operating system are you using?
Host: Ubuntu 16.04
Target: Openwrt(Pandorabox)

### What did you do?
交叉编译SSRR-libev

### What did you expect to see?
编译成功

### What did you see instead?
编译失败

### What is your config in detail (with all sensitive info masked)?

编译提示：
In file included from includeobfs.h:4:0,
                 from local.c:111:
obfs/auth_chain.c: In function 'auth_chain_f_init_data_size':
obfs/auth_chain.c:414:23: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
     uint8_t *newKey = (uint8_t) malloc(sizeof(uint8_t) * server->key_len);
                       ^
obfs/auth_chain.c:414:23: error: initialization makes pointer from integer without a cast [-Werror]
obfs/auth_chain.c: In function 'auth_chain_f_set_server_info':
obfs/auth_chain.c:684:46: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
     uint8_t *key_change_datetime_key_bytes = (uint8_t) malloc(sizeof(uint8_t) * 8);
                                              ^
obfs/auth_chain.c:684:46: error: initialization makes pointer from integer without a cast [-Werror]
cc1: all warnings being treated as errors

应该是一个typo，改动为(uint8_t *)后编译成功。因为openwrt的编译工具启用了-Werror，所以编译不过去。
希望更新。

**Comment by chenhw2** [comment]
Already fixed a day ago in https://github.com/shadowsocksrr/shadowsocksr-libev/commit/d4904568c0bd7e0861c0cbfeaa43740f404db214

**Comment by xsm1997** [comment]
Sorry, I'm not using the dev branch. Closing this issue.

**Comment by Akkariiin** [comment]
i will rollback newgest release, please do not use it.
