### ISSUE TITLE
LEDE编译报错 可能是mbedtls版本太高

### ISSUE THREAD

**Issue by daiaji** [shadowsocksrr/shadowsocksr-libev#7]
`checking whether mbedtls supports the Camellia block cipher or not... configure: error: MBEDTLS_CAMELLIA_C required`
报错原因：官方源mbedtls版本太高,应该使用2.4.0
他们是这么说的
LEDE现在用的mbedtls`PKG_VERSION:=2.6.0`
建议跟进

**Comment by chenhw2** [comment]
Use https://github.com/shadowsocks/openwrt-feeds instead.

**Comment by daiaji** [comment]
@chenhw2 问题解决了
但是还是更新一下mbedtls库的版本比较好吧

**Comment by Akkariiin** [comment]
现在正在头疼libev这边的密码学依赖库的版本问题

你能提供一下你的解决方案和详细的相关信息吗

**Comment by chenhw2** [comment]
@Akkariiin https://github.com/shadowsocks/openwrt-feeds/blob/master/base/mbedtls/Makefile
降级？

```mbedtls 2.5.1-2```

**Comment by Akkariiin** [comment]
降级.........................................................

**Comment by daiaji** [comment]
@Akkariiin @chenhw2 别降级😂
我这是编译实在过不了才降级的啊

**Comment by Akkariiin** [comment]
可能要重新组织libev这边的编译框架和依赖库架构。只能慢慢来了。

**Comment by daiaji** [comment]
@Akkariiin 慢慢来吧

**Comment by chenhw2** [comment]
Workd With https://github.com/shadowsocks/openwrt-feeds/commit/d9bc9be7728fd038886b2cac947a69cc88db7b02#diff-9d53d73fdc2415a966f218d62266873d

![2017-10-19 03-49-04](https://user-images.githubusercontent.com/12322033/31739455-82d5652e-b480-11e7-9934-7d3df0300cad.png)

**Comment by lijun0326** [comment]
试试OpenSSL？
![qq 20171019181406](https://user-images.githubusercontent.com/17663689/31766373-f5a6874e-b4f9-11e7-8f04-82652ae5ef85.png)

**Comment by daiaji** [comment]
@lijun0326 用mbedtls的原因很大程度上是openssl的原因

**Comment by panda-mute** [comment]
不是版本原因，是lede的mbedtls patch把这个功能disable掉了，直接去掉那个patch或者改一下patch就可以了

**Comment by daiaji** [comment]
@panda-mute 什么仇什么怨？

**Comment by panda-mute** [comment]
@daiaji 
https://github.com/openwrt-develop/openwrt-shadowsocksr/issues/1

**Comment by cary-zhou** [comment]
在package/libs/mbedtls/patches/200-config.patch下163行，补丁原来是注释掉"MBEDTLS_CAMELLIA_C"宏定义的："+//#define MBEDTLS_CAMELLIA_C"
去掉双斜杠保存重新build就通过了："+#define MBEDTLS_CAMELLIA_C"

**Comment by Akkariiin** [comment]
@cary-zhou thank you~~
